name: Core
on:
  - push

jobs:
  PackSnapshot:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          key: v1_node14.x_ubuntu-latest_${{ github.ref }}_yarn
          path: .yarn/cache
          restore-keys: v1_node14.x_ubuntu-latest_refs/heads/master_yarn
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          key: v1_node14.x_ubuntu-latest_${{ github.ref }}_node-modules
          path: .yarn/cache
          restore-keys: v1_node14.x_ubuntu-latest_refs/heads/master_node-modules
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
      - name: Set up Yarn
        run: npm install -g yarn@^2.0.0-rc.27
      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false'
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: yarn run rollup
      - name: Pack
        run: npm pack
        working-directory: ./dist
      - name: Rename tarball
        run: mv *.tgz dist.tgz
        working-directory: ./dist
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: package.tgz
          path: dist/dist.tgz

  Lint:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          key: v1_node14.x_ubuntu-latest_${{ github.ref }}_yarn
          path: .yarn/cache
          restore-keys: v1_node14.x_ubuntu-latest_refs/heads/master_yarn
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          key: v1_node14.x_ubuntu-latest_${{ github.ref }}_node-modules
          path: .yarn/cache
          restore-keys: v1_node14.x_ubuntu-latest_refs/heads/master_node-modules
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
      - name: Set up Yarn
        run: npm install -g yarn@^2.0.0-rc.27
      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false'
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: yarn run lint

  BuildAndRelease:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          key: v1_node14.x_ubuntu-latest_${{ github.ref }}_yarn
          path: .yarn/cache
          restore-keys: v1_node14.x_ubuntu-latest_refs/heads/master_yarn
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          key: v1_node14.x_ubuntu-latest_${{ github.ref }}_node-modules
          path: .yarn/cache
          restore-keys: v1_node14.x_ubuntu-latest_refs/heads/master_node-modules
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
      - name: Set up Yarn
        run: npm install -g yarn@^2.0.0-rc.27
      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false'
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: yarn run lint
      - name: Build & Release
        run: yarn run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
